version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000" # 默认端口为 8000
    volumes:
      - ./src:/app  # Mount only the src folder
      - ./wait-for-it.sh:/app/wait-for-it.sh  # Mount the wait-for-it.sh script
      - ${MEDIA_ROOT}:/media
      - ${LOG_ROOT}:/logs
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      HOST_NAME: ${HOST_NAME}
    command: >
      sh -c "/app/wait-for-it.sh db:5432 -- python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${MEDIA_ROOT}:/media
      - ${NGINX_LOG_ROOT}:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: