# Generated by Django 5.1.3 on 2025-01-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_current_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerView',
        ),
    ]
